# Increase memory available to Gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# Check versions: https://fabricmc.net/develop/
minecraft_version=26.1
minecraft_version_max=26.1.2
loader_version=0.19.2
loom_version=1.16-SNAPSHOT

# Mod Properties
mod_version=0.4.0
maven_group=me.Madisonn
archives_base_name=Staff-Helper

# Dependencies
fabric_api_version=0.145.1+26.1
fzzy_version=0.7.6+26.1